version: '2'
services:
    app:
        build: .
        depends_on:
            - database
            - flower
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - ./etc/app:/opt/app/etc
            - ./tmp:/opt/app/tmp
            - ./static:/opt/app/static
            - ./project:/opt/app/project
        networks:
            - database
            - redis

    nginx:
        image: nginx:stable-alpine
        depends_on:
            - app
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./static:/opt/app/static
            - ./tmp:/opt/app/tmp
            - ./data/letsencrypt:/etc/letsencrypt
        networks:
            - nginx

    database:
        image: postgres:10.10
        env_file:
            - .env
        ports:
            - 45637:5432
        volumes:
            - ./data/database:/var/lib/postgresql/data
        networks:
            - database

    redis:
        image: redis:5.0.9-alpine3.12
        volumes:
            - ./var/redis:/data/data
            - ./log/redis:/data/logs
            - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            - redis

    flower:
        build: ./etc/flower
        depends_on:
            - redis
        env_file:
            - .env
        volumes:
            - ./log/flower:/logs
        command: flower --url-prefix=/flower --basic_auth=$FLOWER_LOGIN:$FLOWER_PASSWORD --port=5555 --broker=$BROKER_URI
        networks:
            - redis
            - nginx

    celery:
        build: .
        env_file:
            - .env
        command: sh -c "cd /opt/app/project && celery -A project worker -n celery@%h -c 2 -B -E -s /tmp/celery.%t"
        volumes:
            - ./project:/opt/app/project
            - ./tmp:/opt/app/tmp
        depends_on:
            - redis
        networks:
            - redis
            - database

networks:
    nginx:
        driver: bridge
    database:
        driver: bridge
    redis:
        driver: bridge
